package com.demo.commons.restclient.utils;

import com.demo.commons.properties.restclient.HeaderTemplate;
import com.demo.commons.tracing.enums.TraceParam;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.function.Consumer;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class HeadersFiller {

  public static Map<String, String> fillHeaders(HeaderTemplate headerTemplate,
                                                Map<String, String> currentHeaders) {

    Consumer<Map<String, String>> providedHeaders = ParameterMapFiller.addProvidedParams(headerTemplate.getProvided());
    Consumer<Map<String, String>> generatedHeaders = ParameterMapFiller.addGeneratedParams(headerTemplate.getAutoGenerated());
    Consumer<Map<String, String>> forwardedHeaders = ParameterMapFiller.addForwardedParams(headerTemplate.getForwarded(), currentHeaders);
    Consumer<Map<String, String>> traceHeaders = addTraceHeaders(headerTemplate.getTracing(), currentHeaders);

    Map<String, String> headers = new HashMap<>();
    providedHeaders.accept(headers);
    generatedHeaders.accept(headers);
    forwardedHeaders.accept(headers);
    traceHeaders.accept(headers);

    return headers;
  }

  private static Consumer<Map<String, String>> addTraceHeaders(Map<String, TraceParam> traceHeaders,
                                                               Map<String, String> currentHeaders) {

    return headers -> Optional.ofNullable(traceHeaders).ifPresent(headerMap -> headerMap
        .forEach((headerKey, traceParam) -> {
          Optional.ofNullable(currentHeaders.get(traceParam.getKey()))
              .ifPresent(traceField -> headers.put(traceParam.getKey(), traceParam.getGenerator().apply(traceField)));
        }));
  }
}